application: redactedtweet
version: 1
runtime: python27
api_version: 1

handlers:
- url: /
  script: helloworld.py

- url: /tasks/redactify
  script: redacted_wrapper.py

- url: /tasks/libify
  script: madlib_wrapper.py
